### PR TITLE
Sorted the Arabic countries first and updated COUNTRIES_OVERRIDE

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Description

TASK: [Update the django-countries dependency to include COUNTRIES_FIRST_SORT feature](https://app.asana.com/0/256944342521670/303375741516933)

### Related PRs
 - https://github.com/Edraak/edx-platform/pull/201
 - https://github.com/Edraak/edx-platform/pull/94
 - https://github.com/Edraak/edx-platform/pull/90

### TODO
 - [x] Unit tests
 - [x] Smoke tests 

### Testing this PR
 - Make sure you re-install the prerequisites using 

```
$ NO_PREREQ_INSTALL=false paver install_prereqs
```

### Dependency
~~The dependency `django-countries==4.0` is already fulfilled at [Ficus](https://github.com/edx/edx-platform/blob/master/requirements/edx/base.txt), therefore, we don't need an OSPR for it.~~ Now it's 4.4 but edX will likely reject the PR as an out-of-product-scope.

## Screenshot
image

### CODE REVIEW

**Review by Salomari1987 — COMMENTED** [review]
@OmarIthawi did you smoke test?

**Comment by OmarIthawi** [comment]
@Salomari1987 don't know! I'll test it and let you know.

**Comment by OmarIthawi** [comment]
Now I did @Salomari1987.

**Comment by Salomari1987** [comment]
Merging ...

**Review by Salomari1987 — APPROVED** [review]

**Comment by OmarIthawi** [comment]
🎉

**Pull request merged**
