### PR TITLE
Migrate edraak_ratelimit module

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Description

Task: [Migrate the edraak_ratelimit module with a feature flag](https://app.asana.com/0/256944342521670/280828993308195)

Migrated the `edraak_ratelimit` module with tests and code quality fixes.

### CODE REVIEW

**Comment by Salomari1987** [comment]
First look, zero comments. Good job!

**Comment by OmarIthawi** [comment]
Really? Happy to hear that @Salomari1987!

**Review by Salomari1987 — APPROVED** [review]
It all looks good, tested on local, and code reviewed. Ready to merge

**Comment by OmarIthawi** [comment]
~~Thanks @Salomari1987 please feel free to merge. If something's came up, I'll fix it in a future pull request.~~ Had to update the `AUTHENTICATION_BACKEND` settings handling.

**Comment by OmarIthawi** [comment]
@Salomari1987 I've updated the way `AUTHENTICAITON_BACKENDS` being updated. Could you please review and smoke test? Other than this the PR is ready from my side.

**Comment by OmarIthawi** [comment]
Reopened as #43

**Pull request closed without merging**
