### PR TITLE
Sync with Ficus

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Description

TASK: [Merge with Ficus](https://app.asana.com/0/256944342521670/316199090826703)

Trying to do a reproducible almost headache-free sync with edX.

### Sync Steps
- [x] Create a new branch to start the sync `$ git checkout -b omar/ficus-apr-20th master`
- [x] Disable the Jenkins temporarily
- [x] List Eucalyptus cherry-picks by edX `$ git log --oneline edx/master..open-release/eucalyptus.2`
- [x] [Undo the changes](http://stackoverflow.com/a/21718540/161278) one by one (starting with the most recent ones): `$ git revert --no-commit <COMMIT_SHA>`
- [x] A quick check to make sure we have the [correct changes](http://stackoverflow.com/a/1549155/161278) `$ git merge-base omar/ficus-apr-20th edx/master` then `$ git diff omar/ficus-apr-20th <BASE_SHA>`, manually see the changes.
- [x] Merge with Ficus `$ git merge open-release/ficus.2` (got about 12 conflicted files, which are perfectly fine)
- [x] Resolve the conflicts (don't push yet!)
- [x] Sanity checks to ensure we're on the right track:
  - `$ git status`
  - Check how many commits we've introduced by the merge (so far 2094 including the merge commit itself).
  - `$ git log --oneline open-release/eucalyptus.2..open-release/ficus.2 | wc -l` The result is 2039 which makes sense to me.
- [x] Push!
- [x] Update Edraak modifications to be compatible with Ficus
- [x] Run on a devstack
- [x] Run Edraak tests (Refer back to `$ git diff <BASE_SHA>` for Edraak modifications)
- [x] Update the Jenkinsfile (and the prepare a compatible Jenkins image, credit goes to @Salomari1987)
- [x] Smoke test to see if we missed something
- [x] Get greenmark checks on all the functional/unit tests

### Extra Steps

 - Merged with `open-release/ficus.master` to solve the [MathJax CDN issue](https://www.mathjax.org/cdn-shutting-down/).
 - Skipped few tests.
 - Code quality checks are meaningless during the upgrade process due to the mechanism `diff_quality` works. 

## Conflicts Found
```
.jshintrc
cms/envs/test.py
common/test/acceptance/tests/lms/test_lms_edxnotes.py
common/test/acceptance/tests/studio/test_studio_components.py
common/test/acceptance/tests/video/test_studio_video_transcript.py
common/test/acceptance/tests/video/test_video_module.py
lms/djangoapps/courseware/views/views.py
lms/djangoapps/instructor_task/tasks_helper.py
lms/djangoapps/instructor_task/tests/test_models.py
lms/envs/test.py
lms/static/sass/_build-course.scss
requirements/edx/base.txt
```

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Hey @Salomari1987 and @ahmedaljazzar. It would be great if you try to review the steps that I've done at your leisure.

I recommend that at least one of you (perhaps @Salomari1987) critically reproduce (i.e. try to see if some steps are incorrect, or suggest an alternative method) the steps in a separate branch and compare the output.

This is a huge step. It's important to avoid the mistakes we've done in https://github.com/Edraak/edx-platform/pull/161 to save ourselves from doing fixups like this one (https://github.com/Edraak/edx-platform/pull/226).

**Comment by iamjazzar** [comment]
I see it's working smoothly, no?

**Comment by OmarIthawi** [comment]
So far @ahmedaljazzar! I still haven't tried to run the tests or CI. 

Other than this, it was acceptably smooth. Since it only took about 30 minutes to resolve the conflicts.

**Comment by OmarIthawi** [comment]
@Edraak/developers:

 - I've disabled the review for this repo because I have no reviewers to work with me. This unfortunately going to happen in future pull requests.
 - I'm merging this branch despite the quality issues, because edX's `diff_quality` does redundant checks for the release update pull requests. In future pull requests this won't happen.

**Comment by iamjazzar** [comment]
Mabrook!

**Pull request merged**
